# Generated by Django 4.2.3 on 2023-07-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='driver',
            field=models.ManyToManyField(to='driver.driver'),
        ),
    ]
