# Generated by Django 4.2.3 on 2023-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='art_piece',
            field=models.ManyToManyField(to='auction.artpiece'),
        ),
    ]
